### ISSUE TITLE
Address the timing issue

### ISSUE THREAD

**Issue by gunesacar** [Paul2803k/TopicsAPICatcher#4]
We seem to miss early calls to Topics API. Let's follow Privacy Badger's example to solve it: 
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/jU3Ib6fP9A8/m/qsLz0HcnAwAJ
https://github.com/EFForg/privacybadger/blob/4b8c4655a4d46c900df99f9837c998bf67d51133/src/js/contentscripts/utils.js#L18-L37

**Comment by Paul2803k** [comment]
I have noticed that the proposed solution raises a CSP infringement in some websites such as [https://www.vuecinemas.nl/#filmposters](url). 
These websites seem to completely prohibit any inline script. I wonder how they played around it...
Here is a screenshot of the error:
![image](https://github.com/Paul2803k/TopicsAPICatcher/assets/44923416/5c61df3a-d613-4602-8b71-5f0e626fb41d)
To mitigate the issue I have injected the script as a `Blob` since it seems to help getting around a few of these restrictions. Some still stand. Any suggestion at the top of your head @gunesacar?
On the other hand, the timing issue seems to be fixed.

**Comment by gunesacar** [comment]
> Any suggestion at the top of your head @gunesacar?

Unfortunately none, but a search for CSP violation Privacy Badger or uBlock Origin yields interesting results:
https://github.com/EFForg/privacybadger/issues/1793

**Comment by gunesacar** [comment]
Just to be clear, I think this is a low priority issue and can be stated as a limitation if a clean workaround cannot be found. What we don't want is to interfere with the websites' CSP policies, for example. Thanks for identifying this bug in the first place!

**Comment by Paul2803k** [comment]
I agree, I will give it some thought but it definitely shouldn't delay the wrap-up.  As you mention, this is an interesting limitation that a lot of extensions face.

> Just to be clear, I think this is a low priority issue and can be stated as a limitation if a clean workaround cannot be found. What we don't want is to interfere with the websites' CSP policies, for example. Thanks for identifying this bug in the first place!
